//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Adı.
        /// </summary>
        public static string BudgetAccount_Label_AccountName {
            get {
                return ResourceManager.GetString("BudgetAccount_Label_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Tipi.
        /// </summary>
        public static string BudgetAccount_Label_AccountType {
            get {
                return ResourceManager.GetString("BudgetAccount_Label_AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Bakiye.
        /// </summary>
        public static string BudgetAccount_Label_CurrentBalance {
            get {
                return ResourceManager.GetString("BudgetAccount_Label_CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string BudgetAccount_Label_GridActions {
            get {
                return ResourceManager.GetString("BudgetAccount_Label_GridActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeye Geri Dön.
        /// </summary>
        public static string BudgetAccount_Link_BackToList {
            get {
                return ResourceManager.GetString("BudgetAccount_Link_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Hesap Oluştur.
        /// </summary>
        public static string BudgetAccount_Link_CreateNewAccount {
            get {
                return ResourceManager.GetString("BudgetAccount_Link_CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string Categories_Label_Name {
            get {
                return ResourceManager.GetString("Categories_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeye Geri Dön.
        /// </summary>
        public static string Categories_Link_BackToList {
            get {
                return ResourceManager.GetString("Categories_Link_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori Ekle.
        /// </summary>
        public static string Categories_Link_CreateNewCategory {
            get {
                return ResourceManager.GetString("Categories_Link_CreateNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Tracker.
        /// </summary>
        public static string ExpenseTracker {
            get {
                return ResourceManager.GetString("ExpenseTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Generic_Save_Button {
            get {
                return ResourceManager.GetString("Generic_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yaparak harcamalarınızı bir güzel takip edebilirsiniz.
        /// </summary>
        public static string Home_LoginDescription {
            get {
                return ResourceManager.GetString("Home_LoginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önce kayıt yaparsanız; giriş yaparak harcamalarınızı bir güzel takip edebilirsiniz.
        /// </summary>
        public static string Home_RegisterDescription {
            get {
                return ResourceManager.GetString("Home_RegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Tracker bir harcama takibi uygulamasıdır. Bu uygulama ile harcamalarınızı kontrol altında tutabilir, hesaplarınızı yöneterek elinizdeki paranızı daha iyi değerlendirmeye başlayabilirsiniz..
        /// </summary>
        public static string Home_Unauthorized_Description {
            get {
                return ResourceManager.GetString("Home_Unauthorized_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresi.
        /// </summary>
        public static string Input_Placeholder_Email {
            get {
                return ResourceManager.GetString("Input_Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Input_Placeholder_Password {
            get {
                return ResourceManager.GetString("Input_Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Login_ButtonLogin {
            get {
                return ResourceManager.GetString("Login_ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisteme giriş yapın.
        /// </summary>
        public static string Login_LoginToStart {
            get {
                return ResourceManager.GetString("Login_LoginToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni bir hesap oluşturun.
        /// </summary>
        public static string Login_NewMembershipLink {
            get {
                return ResourceManager.GetString("Login_NewMembershipLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesaplar.
        /// </summary>
        public static string Menu_Accounts {
            get {
                return ResourceManager.GetString("Menu_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Hesap.
        /// </summary>
        public static string Menu_Accounts_Add {
            get {
                return ResourceManager.GetString("Menu_Accounts_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Hesaplar.
        /// </summary>
        public static string Menu_Accounts_List {
            get {
                return ResourceManager.GetString("Menu_Accounts_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçe Yönetimi.
        /// </summary>
        public static string Menu_BudgetManagement {
            get {
                return ResourceManager.GetString("Menu_BudgetManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçe Planı.
        /// </summary>
        public static string Menu_BudgetPlan {
            get {
                return ResourceManager.GetString("Menu_BudgetPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütçeler.
        /// </summary>
        public static string Menu_Budgets {
            get {
                return ResourceManager.GetString("Menu_Budgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Bütçe Oluştur.
        /// </summary>
        public static string Menu_Budgets_Add {
            get {
                return ResourceManager.GetString("Menu_Budgets_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif Bütçeyi Değiştir.
        /// </summary>
        public static string Menu_Budgets_ChangeActiveBudget {
            get {
                return ResourceManager.GetString("Menu_Budgets_ChangeActiveBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Bütçeler.
        /// </summary>
        public static string Menu_Budgets_List {
            get {
                return ResourceManager.GetString("Menu_Budgets_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Menu_Categories {
            get {
                return ResourceManager.GetString("Menu_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori.
        /// </summary>
        public static string Menu_Category_Add {
            get {
                return ResourceManager.GetString("Menu_Category_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Kategoriler.
        /// </summary>
        public static string Menu_Category_List {
            get {
                return ResourceManager.GetString("Menu_Category_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik.
        /// </summary>
        public static string Menu_MembershipManagement {
            get {
                return ResourceManager.GetString("Menu_MembershipManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni İşlem.
        /// </summary>
        public static string Menu_NewTransaction {
            get {
                return ResourceManager.GetString("Menu_NewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm İşlemler.
        /// </summary>
        public static string Menu_TransactionList {
            get {
                return ResourceManager.GetString("Menu_TransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Nav_Contact {
            get {
                return ResourceManager.GetString("Nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Nav_Login {
            get {
                return ResourceManager.GetString("Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt.
        /// </summary>
        public static string Nav_Register {
            get {
                return ResourceManager.GetString("Nav_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Hesap.
        /// </summary>
        public static string Page_Title_BudgetAccount_Create {
            get {
                return ResourceManager.GetString("Page_Title_BudgetAccount_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Düzenle.
        /// </summary>
        public static string Page_Title_BudgetAccount_Edit {
            get {
                return ResourceManager.GetString("Page_Title_BudgetAccount_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesaplar.
        /// </summary>
        public static string Page_Title_BudgetAccount_Index {
            get {
                return ResourceManager.GetString("Page_Title_BudgetAccount_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori.
        /// </summary>
        public static string Page_Title_Categories_Create {
            get {
                return ResourceManager.GetString("Page_Title_Categories_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Düzenle.
        /// </summary>
        public static string Page_Title_Categories_Edit {
            get {
                return ResourceManager.GetString("Page_Title_Categories_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Page_Title_Categories_Index {
            get {
                return ResourceManager.GetString("Page_Title_Categories_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaten üyeyim. Giriş yap.
        /// </summary>
        public static string Register_AlreadyAMember {
            get {
                return ResourceManager.GetString("Register_AlreadyAMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string Register_Button_Register {
            get {
                return ResourceManager.GetString("Register_Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre (tekrar).
        /// </summary>
        public static string Register_Placeholder_PasswordRepeat {
            get {
                return ResourceManager.GetString("Register_Placeholder_PasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye olun.
        /// </summary>
        public static string Register_RegisterNewMembership {
            get {
                return ResourceManager.GetString("Register_RegisterNewMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özet.
        /// </summary>
        public static string Title_Dashboard_Index {
            get {
                return ResourceManager.GetString("Title_Dashboard_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Title_Login {
            get {
                return ResourceManager.GetString("Title_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Üyelik.
        /// </summary>
        public static string Title_Register {
            get {
                return ResourceManager.GetString("Title_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni İşlem Girişi.
        /// </summary>
        public static string Title_Transaction_Add {
            get {
                return ResourceManager.GetString("Title_Transaction_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Düzenle.
        /// </summary>
        public static string Title_Transaction_Edit {
            get {
                return ResourceManager.GetString("Title_Transaction_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Listesi.
        /// </summary>
        public static string Title_Transaction_List {
            get {
                return ResourceManager.GetString("Title_Transaction_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string Transaction_Delete_Modal_Close {
            get {
                return ResourceManager.GetString("Transaction_Delete_Modal_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Silinecek.
        /// </summary>
        public static string Transaction_Delete_Modal_Header {
            get {
                return ResourceManager.GetString("Transaction_Delete_Modal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string Transaction_Delete_Modal_No {
            get {
                return ResourceManager.GetString("Transaction_Delete_Modal_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlemi silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string Transaction_Delete_Modal_Text {
            get {
                return ResourceManager.GetString("Transaction_Delete_Modal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string Transaction_Delete_Modal_Yes {
            get {
                return ResourceManager.GetString("Transaction_Delete_Modal_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap.
        /// </summary>
        public static string Transaction_Edit_Label_Account {
            get {
                return ResourceManager.GetString("Transaction_Edit_Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        public static string Transaction_Edit_Label_Amount {
            get {
                return ResourceManager.GetString("Transaction_Edit_Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string Transaction_Edit_Label_Category {
            get {
                return ResourceManager.GetString("Transaction_Edit_Label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string Transaction_Edit_Label_Date {
            get {
                return ResourceManager.GetString("Transaction_Edit_Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Transaction_Edit_Label_Description {
            get {
                return ResourceManager.GetString("Transaction_Edit_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider.
        /// </summary>
        public static string Transaction_Edit_Label_Expense {
            get {
                return ResourceManager.GetString("Transaction_Edit_Label_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelir.
        /// </summary>
        public static string Transaction_Edit_Label_Income {
            get {
                return ResourceManager.GetString("Transaction_Edit_Label_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Transaction_Link_Delete {
            get {
                return ResourceManager.GetString("Transaction_Link_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Transaction_Link_Edit {
            get {
                return ResourceManager.GetString("Transaction_Link_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap.
        /// </summary>
        public static string Transaction_List_Label_Account {
            get {
                return ResourceManager.GetString("Transaction_List_Label_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        public static string Transaction_List_Label_Amount {
            get {
                return ResourceManager.GetString("Transaction_List_Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string Transaction_List_Label_Category {
            get {
                return ResourceManager.GetString("Transaction_List_Label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string Transaction_List_Label_Date {
            get {
                return ResourceManager.GetString("Transaction_List_Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Transaction_List_Label_Description {
            get {
                return ResourceManager.GetString("Transaction_List_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Transaction_List_Label_Grid_Actions {
            get {
                return ResourceManager.GetString("Transaction_List_Label_Grid_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonraki Ay.
        /// </summary>
        public static string Transaction_List_Label_NextMonth {
            get {
                return ResourceManager.GetString("Transaction_List_Label_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önceki Ay.
        /// </summary>
        public static string Transaction_List_Label_PreviousMonth {
            get {
                return ResourceManager.GetString("Transaction_List_Label_PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versiyon.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
